FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

# ✅ Install Docker CLI
RUN apt-get update && apt-get install -y docker.io

COPY . .

CMD ["python3", "APIServer.py"]

